// Icon registry.
//
// Specs travel as JSON, so they can only carry an icon *key*. This map is
// the single place a key becomes a component. Anything not in here simply
// doesn't render — a spec can never smuggle arbitrary markup into the UI.
//
// Adding an icon is a one-line entry; no block component ever imports
// from lucide directly.

import {
  AlertTriangle,
  ArrowLeftRight,
  Armchair,
  Ban,
  Banknote,
  Bell,
  BookOpen,
  Building2,
  CalendarClock,
  CalendarDays,
  CalendarPlus,
  Check,
  ChefHat,
  ClipboardList,
  Clock,
  Coins,
  ConciergeBell,
  Croissant,
  CupSoda,
  DoorOpen,
  FileText,
  Filter,
  Flame,
  Gauge,
  Hourglass,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  type LucideIcon,
  MapPin,
  Martini,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Moon,
  NotebookPen,
  Percent,
  PhoneCall,
  Plus,
  PlusCircle,
  Receipt,
  Repeat,
  Salad,
  ScanLine,
  Settings,
  ShoppingBag,
  Soup,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Sunset,
  Table2,
  Tag,
  Ticket,
  Timer,
  TrendingDown,
  TrendingUp,
  Undo2,
  UserCheck,
  UserPlus,
  UserX,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Wine,
  Zap,
} from "lucide-react";

export const ICONS = {
  alert: AlertTriangle,
  armchair: Armchair,
  ban: Ban,
  banknote: Banknote,
  bell: Bell,
  book: BookOpen,
  building: Building2,
  calendar: CalendarDays,
  "calendar-clock": CalendarClock,
  "calendar-plus": CalendarPlus,
  check: Check,
  "chef-hat": ChefHat,
  clipboard: ClipboardList,
  clock: Clock,
  coins: Coins,
  "concierge-bell": ConciergeBell,
  croissant: Croissant,
  "cup-soda": CupSoda,
  "door-open": DoorOpen,
  file: FileText,
  filter: Filter,
  flame: Flame,
  gauge: Gauge,
  grid: LayoutGrid,
  hourglass: Hourglass,
  info: Info,
  layout: LayoutDashboard,
  leaf: Leaf,
  map: MapPin,
  martini: Martini,
  megaphone: Megaphone,
  message: MessageCircle,
  "message-square": MessageSquare,
  moon: Moon,
  note: NotebookPen,
  percent: Percent,
  phone: PhoneCall,
  plus: Plus,
  "plus-circle": PlusCircle,
  receipt: Receipt,
  repeat: Repeat,
  salad: Salad,
  scan: ScanLine,
  settings: Settings,
  shopping: ShoppingBag,
  soup: Soup,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  sunrise: Sunrise,
  sunset: Sunset,
  swap: ArrowLeftRight,
  table: Table2,
  tag: Tag,
  ticket: Ticket,
  timer: Timer,
  "trend-down": TrendingDown,
  "trend-up": TrendingUp,
  undo: Undo2,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "user-x": UserX,
  users: Users,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  wallet: Wallet,
  wine: Wine,
  zap: Zap,
} as const satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICONS;

/** Every key, for the styleguide and for validating a spec from a backend. */
export const ICON_KEYS = Object.keys(ICONS) as IconKey[];

export function resolveIcon(key: IconKey | undefined): LucideIcon | null {
  if (!key) return null;
  return ICONS[key] ?? null;
}
